### ISSUE TITLE
Build a database model for customers

### ISSUE THREAD

**Issue by elien2016** [CSCI-GA-2820-FA23-003/customers#2]
**As a** user of the API (e.g. Customer Support, Analyst, etc.)
**I need** information on customers
**So that** I can help the customers or make analyses
   
 ### Details and Assumptions
 * Model definitions should be held in models.py
 * Python, SQLAlchemy and PostgreSQL will be used
 * At a minimum it should have the customer’s first and last name, along with some customer id that can be used as a key for uniquely identifying them
 * Customers also have at least one address
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the database model has been built and some dummy entries added
 When I query for a customer
 Then at a minimum I should get the customer's first and last name, address, and a uniquely identifying id
```

**Comment by elien2016** [comment]
@SixingZhou mentioned to me, when we were discussing issue #9, about a checking account column since we're building an ecommerce app. I think for the sake of MVP and other various reasons (e.g. security, you probably don't want to store plain checking account numbers of your customers in the database; if we store a hash of those, the validity check when a customer wants to update this info mentioned in issue #9 would be more involved), I will leave it off for now.

**Comment by Andision** [comment]
Finished in #16
